Crud/urls.py
from django.contrib import admin
from django.urls import path
from grid.views import addnew, index , edit, update, delete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('addnew', addnew, name='addnew'),
    path('edit/<int:id>', edit, name='edit'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', delete, name='delete')
]

grid/models.py
from tabnanny import verbose
from django.db import models

class Employer(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    contact = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

class Student(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()
    email = models.EmailField()

    def __str__(self) -> str:
        return self.first_name

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'
        

grid/forms.py
from django import forms
from .models import Employer


class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'})
        }
        

grid/views.py
from django.shortcuts import render, redirect
from .models import Employer
from .forms import EmployerForm


def addnew(request):
    if request.method == 'POST':
        form = EmployerForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')
            except:
                pass
    else:
        form = EmployerForm()
        return render(request, 'index.html', {'form': form})

def index(request):
    employers = Employer.objects.all()
    return render(request, 'show.html', {'employers':employers})


def edit(request, id):
    employer = Employer.objects.get(id=id)
    context = {'employer': employer}
    return render(request, 'edit.html', context)

def update(request, id):
    employer = Employer.objects.get(id=id)
    form = EmployerForm(request.POST, instance=employer)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'employer':employer})

def delete(request, id):
    employer = Employer.objects.get(id=id)
    employer.delete()
    return redirect('/')

def homepage(request):
    if request.method == '/homepage':
        form = EmployerForm(request.homepage)
        if form.is_valid():
            try:
                form.save()
                return redirect('/homepage')
            except:
                pass
    else:
        form = EmployerForm()
        return render(request, 'index.html', {'form': form})

grid/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<style>
    body {
	background-image: url('https://wallpaper.dog/large/20352933.jpg');
  
  height: 800px; /* You must set a specified height */
  background-position: center; /* Center the image */
  background-repeat: no-repeat; /* Do not repeat the image */
  background-size: cover; /* Resize the background image to cover the entire container */
}
</style>
</head>
<body>
<div class="container">
    <div class="row">
        {%block content%} {%endblock%}
    </div>
</div>
<script>
    $(document).ready(function() {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
       }
    );
} );
</script>
</body>
</html>

grid/templates/edit.html
{%extends 'base.html' %}
{%block title%} Edit Employer{%endblock title%}
{% block content %}
    <div class="col-md-12">
        <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4>
        <form method="POST" class="post-form" action="/update/{{ employer.id }}">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Update Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Id:</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
                               value="{{ employer.id }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employer Name:</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" name="name" id="id_name" required maxlength="100"
                               value="{{ employer.name }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Email:</label>
                    <div class="col-sm-4">
                        <input type="email" class="form-control" name="email" id="id_email" required maxlength="254"
                               value="{{ employer.email }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Contact:</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15"
                               value="{{ employer.contact }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success btn-lg">Update</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

grid/templates/index.html
{% extends 'base.html'%}
{%block title%} Add new employer{%endblock title%}
{%block content%}
<div class="col-md-12">
    <h4>Django CRUD(create read update delete)</h4>
    <form method="POST" class="post-form" action="/addnew">

        {% csrf_token %}

        <div class="container">

            <br>

            <div class="form-group row">

                <label class="col-sm-1 col-form-label"></label>

                <div class="col-sm-4">

                    <h3>Enter Details</h3>

                </div>

            </div>




            <div class="form-group row">

                <label class="col-sm-2 col-form-label">Employee Name:</label>

                <div class="col-sm-4">

                    {{ form.name }}

                </div>

            </div>

            <div class="form-group row">

                <label class="col-sm-2 col-form-label">Employee Email:</label>

                <div class="col-sm-4">

                    {{ form.email }}

                </div>

            </div>

            <div class="form-group row">

                <label class="col-sm-2 col-form-label">Employee Contact:</label>

                <div class="col-sm-4">

                    {{ form.contact }}

                </div>

            </div>

            <div class="form-group row">

                <label class="col-sm-1 col-form-label"></label>

                <div class="col-sm-4">

                    <button type="submit" class="btn btn-primary">Submit</button>

                </div>

            </div>

        </div>

    </form>

</div>

{% endblock content %}

grid/templates/show.html
{%extends 'base.html'%}
{%block title%}Employer Records{%endblock title%}

{%block content%}
<div class="col-md-12">
    <h4> Django CRUD</h4> <span><a href="/addnew" class="btn btn-primary">Add new record</a></span>
    <button> <span><a href="/student" class="btn btn-primary">Student table</a></span> </button>
    <button> <span><a href="/employer" class="btn btn-primary">Employer table</a></span> </button>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
            <th bgcolor="#FFFFFF"><input type="checkbox" id="checkall"/></th>
            <th bgcolor="#FFFFFF">ID</th>
            <th bgcolor="#FFFFFF">Employee Name</th>
            <th bgcolor="#FFFFFF">Employee Email</th>
            <th bgcolor="#FFFFFF">Employee Contact</th>
            <th bgcolor="#FFFFFF">Edit</th>
            <th bgcolor="#FFFFFF">Delete</th>
            </thead>
            <tbody>
            {%for i in employers%}
            <tr>
                <td bgcolor="#FFFFFF"><input type="checkbox" class="checklist"/></td>
                <td bgcolor="#FFFFFF">{{i.id}}</td>
                <td bgcolor="#FFFFFF">{{i.name}}</td>
                <td bgcolor="#FFFFFF">{{i.email}}</td>
                <td bgcolor="#FFFFFF">{{i.contact}}</td>
                <td bgcolor="#FFFFFF"><p data-placement="top" data-toggle="tooltip" title="Edit"><a href=" {% url 'edit' i.id %}"
                    class="btn btn-primary btn-xs"
                    data-title="Edit"
                    data-toggle="modal"
                    data-target="#edit"><span
class="glyphicon glyphicon-pencil"></span></a></p></td>
<td bgcolor="#FFFFFF"><p data-placement="top" data-toggle="tooltip" title="Delete">
    <a href="/delete/{{ i.id }}" class="btn btn-danger btn-xs" data-title="Delete"data-toggle="modal" data-target="#delete">
        <span class="glyphicon glyphicon-trash">
        </span></a></p></td>
</tr>
{% endfor %}
</tbody>

</table>
</div>
</div>
{% endblock content %}